import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage.lifesciences.danaher.com/us/en/products/family/zebron-gc-columns.html', { waitUntil: 'domcontentloaded' , timeout: 90000 });
  await page.getByRole('button', { name: 'Accept All Cookies' }).click();
  await page.getByText('See all product Family in').click();
  await page.locator('#AG0-9201').click();
  await page.locator('#AG0-9201').fill('3');
  await page.locator('#AG0-9201').press('Enter');
  await page.locator('#AG0-9201').click();
//   await page.locator('div').filter({ hasText: /^516 Results$/ }).first().click();
//   await page.locator('#AG0-9201').click();
//   await page.locator('#AG0-9201').click();
//   await page.locator('#AG0-9201').click();
  await page.getByRole('button', { name: 'Buy' }).first().click();
  await page.locator('#closeMiniCart > .h-12 > path').click();
  await page.getByRole('button', { name: 'Quote' }).nth(1).click();
  await page.locator('textarea[name="quote"]').click();
  await page.locator('textarea[name="quote"]').fill('Testing');
  await page.getByRole('button', { name: 'Add and continue browsing' }).click();
  await page.locator('[id="7JM-G001-17"]').click();
  await page.locator('[id="7JM-G001-17"]').fill('2');
  await page.locator('[id="7JM-G001-17"]').press('Enter');
  await page.getByRole('button', { name: 'Buy' }).nth(1).click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('button', { name: 'Quote' }).nth(2).click();
  await page.locator('textarea[name="quote"]').click();
  await page.locator('textarea[name="quote"]').fill('Testing1');
  await page.getByRole('button', { name: 'Add and continue browsing' }).click();

  await page.goto('https://stage.lifesciences.danaher.com/us/en/products/family/visoria-p.html', { waitUntil: 'domcontentloaded' , timeout: 90000 });
  await page.locator('.icon.icon-Rectangle > svg').click();
  await page.locator('#visoria-p-flexacam-c5-transparent-samples-only').click();
  await page.locator('#visoria-p-flexacam-c5-transparent-samples-only').fill('2');
  await page.locator('#visoria-p-flexacam-c5-transparent-samples-only').press('Enter');
  await page.getByRole('button', { name: 'Buy' }).nth(1).click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('button', { name: 'Quote' }).nth(1).click();
  await page.locator('textarea[name="quote"]').click();
  await page.locator('textarea[name="quote"]').fill('Testing2');
  await page.getByRole('button', { name: 'Add and continue browsing' }).click();
  await page.getByRole('button', { name: 'Buy' }).nth(2).click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('button', { name: 'Quote' }).nth(3).click();
  await page.locator('textarea[name="quote"]').click();
  await page.locator('textarea[name="quote"]').fill('Testing4');
  await page.getByRole('button', { name: 'Add and continue browsing' }).click();
  await page.getByRole('link', { name: 'Cart' }).click();
});